# Generated by Django 5.2.3 on 2025-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('dept_code', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('condominium_expenses', models.FloatField()),
            ],
        ),
    ]
